# Generated by Django 5.2.5 on 2025-08-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
