# Generated by Django 5.2.5 on 2025-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('price', models.FloatField(verbose_name='Price')),
                ('detail', models.TextField(verbose_name='Detail')),
            ],
        ),
    ]
