# Generated by Django 5.2.5 on 2025-09-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
