# Generated by Django 5.2.5 on 2025-09-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
