# Generated by Django 5.2.5 on 2025-09-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='rating',
        ),
    ]
