# Generated by Django 5.2.5 on 2025-09-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_stars_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='timeStamp',
        ),
    ]
