# Generated by Django 5.2.5 on 2025-09-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_created_at_review_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='timeStamp',
            new_name='created_at',
        ),
    ]
