# Generated by Django 5.2.5 on 2025-09-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_biding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biding',
            name='bid_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Bid_amount'),
        ),
    ]
