# Generated by Django 5.2.5 on 2025-09-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_biding_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biding',
            name='bid_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Bid Amount'),
        ),
    ]
