# Generated by Django 5.2.5 on 2025-09-17 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_biding_bid_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='biding',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='unique_bid_per_user_per_item'),
        ),
    ]
