# Generated by Django 5.2.5 on 2025-09-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_biding_unique_bid_per_user_per_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biding',
            name='bid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bid Amount'),
        ),
    ]
