# Generated by Django 5.2.5 on 2025-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_biding_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount'),
        ),
    ]
