# Generated by Django 5.2.5 on 2025-10-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_item_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='boolean',
            field=models.BooleanField(default=True),
        ),
    ]
