# Generated by Django 5.2.5 on 2025-10-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_item_boolean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='boolean',
            new_name='is_bidding_open',
        ),
    ]
