# Generated by Django 5.2.5 on 2025-10-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_rename_boolean_item_is_bidding_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_bidding_open',
        ),
        migrations.AddField(
            model_name='item',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
